/*
 * app_soil_sensor.c
 *
 * Ties together the I2C sensor driver, the RAM history buffer and the
 * GATT profile: every 5 minutes, reads the sensor, stores the sample,
 * and notifies any subscribed BLE client.
 */

#include <stddef.h>

#include "ti/ble/app_util/framework/bleapputil_api.h"
#include "ti/ble/app_util/common/util.h"
#include "ti/ble/app_util/menu/menu_module.h"
#include <app_main.h>

#include "soil_sensor.h"
#include "soil_history.h"
#include "battery_gauge.h"
#include "Profiles/soil_sensor_profile.h"
#include "Profiles/battery_service.h"
#include <ti/ble/services/dev_info/dev_info_service.h>
#include "ti/ble/app_util/sw_update/sw_update.h"

#define SOIL_SAMPLE_PERIOD_MS 600000u /* 10 minutes */

static Clock_Struct soilSampleClock;
static uint32_t soilUptimeSec = 0;
static bool soilSensorReady = false;
static bool batteryGaugeReady = false;

static void SoilSensor_takeSample(char *pData);
static void SoilSensor_clockCB(uint32_t arg);
static void SoilSensor_reportFwVersion(void);
static uint8_t appendUintDecimal(uint8_t *buf, uint8_t pos, uint32_t value);

/*********************************************************************
 * @fn      SoilSensor_start
 *
 * @brief   Called after BLE stack init: brings up the I2C sensor,
 *          registers the GATT service and starts the 5-minute sampling
 *          clock.
 *
 * @return  SUCCESS or stack call status
 */
bStatus_t SoilSensor_start(void)
{
    bStatus_t status;

    SoilHistory_init();

    status = SoilSensorProfile_addService();
    if (status != SUCCESS)
    {
        return status;
    }

    // Battery level and power state are exposed over the standard BLE
    // Battery Service (0x180F / 0x2A19 / 0x2A1A) rather than characteristics
    // on the custom soil sensor profile, since these are BLE SIG-adopted
    // characteristics most clients (including Android's own BLE stack)
    // already recognize.
    status = BatteryService_addService();
    if (status != SUCCESS)
    {
        return status;
    }

    // Device Information Service (0x180A) itself is registered earlier by
    // DevInfo_start() in app_main.c - just publish our version into its
    // existing Firmware Revision String characteristic (0x2A26).
    SoilSensor_reportFwVersion();

    soilSensorReady = SoilSensor_init();
    if (!soilSensorReady)
    {
        MenuModule_printf(APP_MENU_PROFILE_STATUS_LINE, 0,
                          "Soil sensor: I2C init FAILED - check wiring");
    }

    batteryGaugeReady = BatteryGauge_init(SoilSensor_getI2CHandle());
    if (!batteryGaugeReady)
    {
        MenuModule_printf(APP_MENU_PROFILE_STATUS_LINE1, 0,
                          "Battery gauge: not detected (BOOSTXL-BATPAKMKII attached?)");
    }

    Util_constructClock(&soilSampleClock, SoilSensor_clockCB,
                        SOIL_SAMPLE_PERIOD_MS, SOIL_SAMPLE_PERIOD_MS, TRUE, 0);

    // Take a first sample immediately rather than waiting 5 minutes
    BLEAppUtil_invokeFunctionNoData(SoilSensor_takeSample);

    return SUCCESS;
}

/*********************************************************************
 * @fn      appendUintDecimal
 *
 * @brief   Appends the decimal ASCII representation of value to buf at
 *          pos, returning the new pos. No bounds checking - callers size
 *          buf generously (see SoilSensor_reportFwVersion).
 */
static uint8_t appendUintDecimal(uint8_t *buf, uint8_t pos, uint32_t value)
{
    char digits[10];
    uint8_t n = 0;

    if (value == 0)
    {
        buf[pos++] = '0';
        return pos;
    }

    while (value > 0)
    {
        digits[n++] = '0' + (value % 10);
        value /= 10;
    }
    while (n > 0)
    {
        buf[pos++] = digits[--n];
    }
    return pos;
}

/*********************************************************************
 * @fn      SoilSensor_reportFwVersion
 *
 * @brief   Reads this image's own version from its MCUboot header
 *          (APP_HDR_ADDR, generated by SysConfig from the OAD app-slot
 *          address - see cc2340_freertos.cmd) and publishes it as
 *          "major.minor.revision" over the standard Device Information
 *          Service's Firmware Revision String characteristic (0x2A26).
 *          A locked-down (secure-boot) header is always valid here: if
 *          this code is executing, the bootloader already verified it.
 */
static void SoilSensor_reportFwVersion(void)
{
    const struct image_header *hdr = (const struct image_header *)APP_HDR_ADDR;
    uint8_t versionStr[DEVINFO_STR_ATTR_LEN];
    uint8_t pos = 0;

    pos = appendUintDecimal(versionStr, pos, hdr->ih_ver.iv_major);
    versionStr[pos++] = '.';
    pos = appendUintDecimal(versionStr, pos, hdr->ih_ver.iv_minor);
    versionStr[pos++] = '.';
    pos = appendUintDecimal(versionStr, pos, hdr->ih_ver.iv_revision);

    DevInfo_setParameter(DEVINFO_FIRMWARE_REV, pos, versionStr);
}

/*********************************************************************
 * @fn      SoilSensor_clockCB
 *
 * @brief   Fires every 5 minutes from timer/Swi context. Defers the
 *          actual (blocking) I2C read to the BLE application task.
 */
static void SoilSensor_clockCB(uint32_t arg)
{
    BLEAppUtil_invokeFunctionNoData(SoilSensor_takeSample);
}

/*********************************************************************
 * @fn      SoilSensor_takeSample
 *
 * @brief   Runs in the BLE application task context. Reads the sensor,
 *          appends to the history buffer, updates HISTORY_COUNT and
 *          notifies CURRENT_READING to any subscribed client, then
 *          reports battery level/status at the same cadence to save
 *          power (no separate fast poll for the battery gauge).
 */
static void SoilSensor_takeSample(char *pData)
{
    SoilSensor_Record_t record;
    uint16_t moistureRaw;
    int16_t tempCentiC;
    uint16_t historyCount;
    uint8_t batteryPercent;

    soilUptimeSec += SOIL_SAMPLE_PERIOD_MS / 1000;

    // Independent peripheral from the soil sensor - read and notify it
    // regardless of whether the soil sensor read below succeeds.
    if (batteryGaugeReady && BatteryGauge_read(&batteryPercent))
    {
        uint16_t flags = 0;
        int16_t averageMa = 0;
        bool present, discharging, charging;
        uint8_t powerState;

        BatteryService_setParameter(BATTERY_SERVICE_LEVEL_ID, sizeof(batteryPercent), &batteryPercent);

        BatteryGauge_readFlags(&flags);
        BatteryGauge_readAverageCurrentMa(&averageMa);

        // Flags() DSG is the gauge's own (hysteresis-filtered) call on
        // discharge direction - more reliable than eyeballing the raw
        // instantaneous AverageCurrent() sign, which can jitter near zero.
        present = (flags & BATTERY_GAUGE_FLAG_BAT_DET) != 0;
        discharging = (flags & BATTERY_GAUGE_FLAG_DSG) != 0;
        charging = !discharging && averageMa > 0;

        powerState = BATTERY_SERVICE_PACK_POWER_STATE(
            present ? BATTERY_SERVICE_PRESENT_PRESENT : BATTERY_SERVICE_PRESENT_NOT_PRESENT,
            discharging ? BATTERY_SERVICE_DISCHARGE_DISCHARGING : BATTERY_SERVICE_DISCHARGE_NOT_DISCHARGING,
            charging ? BATTERY_SERVICE_CHARGING_CHARGING : BATTERY_SERVICE_CHARGING_NOT_CHARGING,
            batteryPercent < 10 ? BATTERY_SERVICE_LEVEL_STATE_CRITICAL : BATTERY_SERVICE_LEVEL_STATE_GOOD);
        BatteryService_setParameter(BATTERY_SERVICE_POWER_STATE_ID, sizeof(powerState), &powerState);

        MenuModule_printf(APP_MENU_PROFILE_STATUS_LINE1, 0,
                          "Battery: %d%% (%s)", batteryPercent,
                          charging ? "charging" : (discharging ? "discharging" : "idle"));
    }

    if (!soilSensorReady || !SoilSensor_read(&moistureRaw, &tempCentiC))
    {
        MenuModule_printf(APP_MENU_PROFILE_STATUS_LINE, 0,
                          "Soil sensor: read FAILED");
        return;
    }

    record.uptimeSec = soilUptimeSec;
    record.moistureRaw = moistureRaw;
    record.tempCentiC = tempCentiC;

    SoilHistory_add(&record);

    historyCount = SoilHistory_getCount();
    uint32_t historyBaseSeq = SoilHistory_getBaseSeq();
    SoilSensorProfile_setParameter(SOILSENSORPROFILE_HISTORY_COUNT, sizeof(historyCount), &historyCount);
    SoilSensorProfile_setParameter(SOILSENSORPROFILE_HISTORY_BASE_SEQ, sizeof(historyBaseSeq), &historyBaseSeq);
    SoilSensorProfile_setParameter(SOILSENSORPROFILE_CURRENT_READING, sizeof(record), &record);

    MenuModule_printf(APP_MENU_PROFILE_STATUS_LINE, 0,
                      "Soil: moisture=%d temp=%d.%02dC",
                      moistureRaw, tempCentiC / 100, tempCentiC % 100);
}
